.TH "DrawingVisitor" 3 "Mon Oct 28 2019" "Video Game Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DrawingVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDrawingVisitor\fP (std::shared_ptr< sf::RenderWindow > w)"
.br
.ti -1c
.RI "virtual void \fBvisit\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project from the source code\&.
