.TH "ForceVisitor" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ForceVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBvisit\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.RI "update force data on sprite (move it dx/dy) "
.ti -1c
.RI "void \fBapplyForce\fP (std::shared_ptr< \fBSpriteProxy\fP > s, double magnitude, float angle)"
.br
.RI "apply a force to the sprite "
.ti -1c
.RI "void \fBstop\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.RI "Stop the sprite from moving\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ForceVisitor::applyForce (std::shared_ptr< \fBSpriteProxy\fP > s, double magnitude, float angle)"

.PP
apply a force to the sprite 
.PP
\fBParameters\fP
.RS 4
\fIs\fP sprite to be operated on 
.br
\fImagnitude\fP force magnitude 
.br
\fIangle\fP angle of operation, in degrees 
.RE
.PP

.SS "void ForceVisitor::stop (std::shared_ptr< \fBSpriteProxy\fP > s)"

.PP
Stop the sprite from moving\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP

.SS "void ForceVisitor::visit (std::shared_ptr< \fBSpriteProxy\fP > s)\fC [virtual]\fP"

.PP
update force data on sprite (move it dx/dy) 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP

.PP
Reimplemented from \fBVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
