.TH "GameEngine" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameEngine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameEngine\fP ()"
.br
.RI "Construct a new Game Engine object\&. "
.ti -1c
.RI "\fB~GameEngine\fP ()"
.br
.RI "Destroy the Game Engine object\&. "
.ti -1c
.RI "void \fBaddVisitor\fP (std::shared_ptr< \fBVisitor\fP >)"
.br
.RI "Add visitor operation for scene\&. "
.ti -1c
.RI "void \fBaddSprite\fP (std::shared_ptr< \fBSpriteProxy\fP >)"
.br
.RI "Add Sprite to scene\&. "
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.RI "Let visitors visit the scene\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameEngine::GameEngine ()"

.PP
Construct a new Game Engine object\&. 
.SS "GameEngine::~GameEngine ()"

.PP
Destroy the Game Engine object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void GameEngine::addSprite (std::shared_ptr< \fBSpriteProxy\fP > s)"

.PP
Add Sprite to scene\&. 
.SS "void GameEngine::addVisitor (std::shared_ptr< \fBVisitor\fP > v)"

.PP
Add visitor operation for scene\&. 
.SS "void GameEngine::update ()"

.PP
Let visitors visit the scene\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
