.TH "GravityVisitor" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GravityVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGravityVisitor\fP (double intensity)"
.br
.RI "Construct a new Gravity \fBVisitor\fP object\&. "
.ti -1c
.RI "void \fBvisit\fP (std::shared_ptr< \fBSpriteProxy\fP >)"
.br
.RI "add arbitrary dy up to move sprite simulating gravity "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GravityVisitor::GravityVisitor (double intensity)"

.PP
Construct a new Gravity \fBVisitor\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIintensity\fP intensity of gravity 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void GravityVisitor::visit (std::shared_ptr< \fBSpriteProxy\fP > s)\fC [virtual]\fP"

.PP
add arbitrary dy up to move sprite simulating gravity 
.PP
Reimplemented from \fBVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
