.TH "GravityVisitor" 3 "Mon Oct 28 2019" "Video Game Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GravityVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGravityVisitor\fP (double intensity)"
.br
.RI "Construct a new Gravity \fBVisitor\fP object\&. "
.ti -1c
.RI "void \fBvisit\fP (std::shared_ptr< \fBSpriteProxy\fP >)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GravityVisitor::GravityVisitor (double intensity)"

.PP
Construct a new Gravity \fBVisitor\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIintensity\fP intensity of gravity 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project from the source code\&.
