.TH "Scene" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScene\fP ()"
.br
.RI "Construct a new \fBScene\fP object\&. "
.ti -1c
.RI "\fB~Scene\fP ()"
.br
.RI "Destroy the \fBScene\fP object\&. "
.ti -1c
.RI "void \fBaddSprite\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.RI "add a sprite to the scene "
.ti -1c
.RI "void \fBaccept\fP (std::shared_ptr< \fBVisitor\fP > v)"
.br
.RI "iterate through sprites in scene letting each visitor visit sprites "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Scene::Scene ()"

.PP
Construct a new \fBScene\fP object\&. 
.SS "Scene::~Scene ()"

.PP
Destroy the \fBScene\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Scene::accept (std::shared_ptr< \fBVisitor\fP > v)"

.PP
iterate through sprites in scene letting each visitor visit sprites 
.PP
\fBParameters\fP
.RS 4
\fIv\fP 
.RE
.PP

.SS "void Scene::addSprite (std::shared_ptr< \fBSpriteProxy\fP > s)"

.PP
add a sprite to the scene 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
