.TH "Scene" 3 "Mon Oct 28 2019" "Video Game Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddSprite\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.ti -1c
.RI "void \fBaccept\fP (std::shared_ptr< \fBVisitor\fP > v)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project from the source code\&.
