.TH "SpriteProxy" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteProxy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpriteProxy\fP ()"
.br
.RI "Construct a new Sprite object\&. "
.ti -1c
.RI "\fBSpriteProxy\fP (std::string \fBtextureLoc\fP, int \fBx\fP, int \fBy\fP, int \fBwidth\fP, int \fBheight\fP)"
.br
.RI "Construct a new Sprite object\&. "
.ti -1c
.RI "int \fBgetX\fP ()"
.br
.ti -1c
.RI "int \fBgetY\fP ()"
.br
.ti -1c
.RI "void \fBsetXY\fP (int X, int Y)"
.br
.RI "set new coords of sprite "
.ti -1c
.RI "double \fBgetDX\fP ()"
.br
.RI "get dx "
.ti -1c
.RI "double \fBgetDY\fP ()"
.br
.RI "get dy "
.ti -1c
.RI "void \fBsetDXY\fP (double \fBx\fP, double \fBy\fP)"
.br
.RI "set dx and dy "
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.RI "Get the Height object\&. "
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.RI "Get the Width object\&. "
.ti -1c
.RI "std::string \fBgetTextureLocation\fP ()"
.br
.RI "Get the Texture Location object\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "x position "
.ti -1c
.RI "int \fBdx\fP"
.br
.RI "change in x ; updated on interval in forceVisitor TODO: perhaps update dx not on force visitor? "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "y position "
.ti -1c
.RI "int \fBdy\fP"
.br
.RI "change in y ; updated on interval in forceVisitor TODO: perhaps update dy not on force visitor? "
.ti -1c
.RI "int \fBheight\fP"
.br
.RI "height of sprite "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "width of sprite "
.ti -1c
.RI "std::string \fBtextureLoc\fP"
.br
.RI "location of image for sprite texture "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpriteProxy::SpriteProxy ()"

.PP
Construct a new Sprite object\&. 
.SS "SpriteProxy::SpriteProxy (std::string textureLoc, int x, int y, int width, int height)"

.PP
Construct a new Sprite object\&. 
.PP
\fBParameters\fP
.RS 4
\fItextureLoc\fP : file location for texture 
.br
\fIx\fP : x location of sprite relative to size of window 
.br
\fIy\fP : y location of sprite relative to size of window 
.br
\fIwidth\fP : width of sprite in pixels 
.br
\fIheight\fP : height of sprite in pixels 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double SpriteProxy::getDX ()"

.PP
get dx 
.PP
\fBReturns\fP
.RS 4
double 
.RE
.PP

.SS "double SpriteProxy::getDY ()"

.PP
get dy 
.PP
\fBReturns\fP
.RS 4
double 
.RE
.PP

.SS "int SpriteProxy::getHeight ()"

.PP
Get the Height object\&. 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "std::string SpriteProxy::getTextureLocation ()"

.PP
Get the Texture Location object\&. 
.PP
\fBReturns\fP
.RS 4
std::string 
.RE
.PP

.SS "int SpriteProxy::getWidth ()"

.PP
Get the Width object\&. 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "int SpriteProxy::getX ()"

.PP
\fBReturns\fP
.RS 4
int x position of sprite 
.RE
.PP

.SS "int SpriteProxy::getY ()"

.PP
\fBReturns\fP
.RS 4
int y Position of sprite 
.RE
.PP

.SS "void SpriteProxy::setDXY (double x, double y)"

.PP
set dx and dy 
.PP
\fBParameters\fP
.RS 4
\fIx\fP new dx 
.br
\fIy\fP new dy 
.RE
.PP

.SS "void SpriteProxy::setXY (int X, int Y)"

.PP
set new coords of sprite 
.PP
\fBParameters\fP
.RS 4
\fIX\fP new X value of Sprite 
.br
\fIY\fP new Y value of Sprite 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int SpriteProxy::dx\fC [protected]\fP"

.PP
change in x ; updated on interval in forceVisitor TODO: perhaps update dx not on force visitor? 
.SS "int SpriteProxy::dy\fC [protected]\fP"

.PP
change in y ; updated on interval in forceVisitor TODO: perhaps update dy not on force visitor? 
.SS "int SpriteProxy::height\fC [protected]\fP"

.PP
height of sprite 
.SS "std::string SpriteProxy::textureLoc\fC [protected]\fP"

.PP
location of image for sprite texture 
.SS "int SpriteProxy::width\fC [protected]\fP"

.PP
width of sprite 
.SS "int SpriteProxy::x\fC [protected]\fP"

.PP
x position 
.SS "int SpriteProxy::y\fC [protected]\fP"

.PP
y position 

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
