.TH "TextSpriteProxy" 3 "Mon Oct 28 2019" "Video Game Final Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextSpriteProxy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSpriteProxy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextSpriteProxy\fP (int x, int y, int fontSize)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "sf::Font \fBmono\fP"
.br
.ti -1c
.RI "sf::Text \fBtext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project from the source code\&.
