.TH "WrapBoundsVisitor" 3 "Fri Nov 8 2019" "Version 1.5" "Video Game Final Project: Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WrapBoundsVisitor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWrapBoundsVisitor\fP (int minX, int maxX, int minY, int maxY)"
.br
.RI "Construct a new Wrap Bounds \fBVisitor\fP object\&. "
.ti -1c
.RI "void \fBvisit\fP (std::shared_ptr< \fBSpriteProxy\fP > s)"
.br
.RI "if sprite is outside of bounds, move it into bounds then have it WRAP "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WrapBoundsVisitor::WrapBoundsVisitor (int minX, int maxX, int minY, int maxY)"

.PP
Construct a new Wrap Bounds \fBVisitor\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIminX\fP minimum X of sprite 
.br
\fImaxX\fP maximum X of sprite 
.br
\fIminY\fP minimum Y of sprite 
.br
\fImaxY\fP maximum Y of sprite 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void WrapBoundsVisitor::visit (std::shared_ptr< \fBSpriteProxy\fP > s)\fC [virtual]\fP"

.PP
if sprite is outside of bounds, move it into bounds then have it WRAP 
.PP
\fBParameters\fP
.RS 4
\fIs\fP 
.RE
.PP

.PP
Reimplemented from \fBVisitor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Game Final Project: Engine from the source code\&.
