@startuml FinalProject
class Game{
    +void start()
}
class GameEngine {
    -list<Visitor> sceneVisitors
    -Scene scene
    +addVisitor(Visitor)
    +addSprite(SpriteProxy)
    +bool update()
}
class Scene{
    -list<SpriteProxy> spriteList
    +void addSprite()
    +void accept()
}
class TextureFactory{
        +bool loadTexture(string);
        +sf::Texture> getTexture(string);
}
class SpriteProxy{
    -int x
    -int y
    -int dy
    -int dx
    -int height
    -int WrapWidth
    -string textureLoc
    +getters()
    +setters()
}
class Visitor{
    +virtual void visit(SpriteProxy)
}
class BounceBoundsVisitor{
    void visit()
}
class WrapBoundsVisitor{
    void visit()
    }
class BoundingBoxCollisionVisitor{
    void visit()
    }
class AbstractRenderer{
    -bool open
    +void draw(vector<SpriteProxy> sp)
    +bool isOpen()
}
class SFMLRenderer{
    -RenderWindow rw
    -TextureFactory tf

}
class AbstractDrawingVisitor{
    -AbstractRenderer renderer
    +void draw()
    +void visit()
    +bool isOpen()
}

class SimpleDrawingVisitor{
    -sf::RenderWindow window
    -map<SpriteProxy,sf::Sprite> text
    }
class GridDrawingVisitor{
    -int maxX
    -int maxY
}
class ForceVisitor{
    void visit()
    }
class GravityVisitor{
    void visit()
    }
class RayCastCollisionVisitor{
    void visit()
    }
hello <--- Game
Game <|-- Pong
Game <|-- Quoridor
Game ---> GameEngine
Game ---> Visitor
Game ---> SpriteProxy
GameEngine --> Visitor
GameEngine --> Scene
Scene <|--- LayeredScene
Scene ---> SpriteProxy
Visitor ---> SpriteProxy
Visitor <|-- ForceVisitor
Visitor <|-- GravityVisitor
Visitor <|-- BounceBoundsVisitor
Visitor <|-- WrapBoundsVisitor
Visitor <|-- BoundingBoxCollisionVisitor
Visitor <|-- RayCastCollisionVisitor
Visitor <|-- AbstractDrawingVisitor
Visitor<|-- AbstractDrawingVisitor
AbstractDrawingVisitor <|-- SimpleDrawingVisitor
AbstractDrawingVisitor <|-- GridDrawingVisitor
AbstractDrawingVisitor ---> AbstractRenderer
AbstractRenderer <|--- SFMLRenderer
AbstractRenderer ---> TextureFactory
@enduml